-- SCRIPT DE ESQUEMA DE BASE DE DATOS PARA CHAT CON IA (v1.0)
-- Este script crea las tablas de configuración de chat e historial de logs.

-- 1. Tabla de Configuración de Chat
CREATE TABLE IF NOT EXISTS public.chat_config (
    id INT PRIMARY KEY DEFAULT 1,
    provider TEXT DEFAULT 'gemini',
    api_key TEXT,
    system_instruction TEXT DEFAULT 'Eres Samanta, el asistente inteligente de Procesa-T CRM. Tienes acceso a los datos de viajes, gastos, choferes y unidades. Ayuda al administrador a consultar la información y registrar gastos o viajes de forma eficiente.',
    model_name TEXT DEFAULT 'gemini-1.5-flash',
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT single_row CHECK (id = 1)
);

-- Insertar configuración por defecto si no existe
INSERT INTO public.chat_config (id, provider, api_key, system_instruction, model_name)
VALUES (1, 'gemini', '', 'Eres Samanta, el asistente inteligente de Procesa-T CRM. Tienes acceso a los datos de viajes, gastos, choferes y unidades. Ayuda al administrador a consultar la información y registrar gastos o viajes de forma eficiente.', 'gemini-1.5-flash')
ON CONFLICT (id) DO NOTHING;

-- 2. Tabla de Logs/Historial de Chat (si no existe ya)
CREATE TABLE IF NOT EXISTS public.chat_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    message TEXT,
    response TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Habilitar Seguridad a Nivel de Fila (RLS)
ALTER TABLE public.chat_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_logs ENABLE ROW LEVEL SECURITY;

-- 4. Crear Políticas de Acceso (RLS)

-- Políticas para chat_config: solo administradores pueden leer y actualizar
DROP POLICY IF EXISTS "Allow admin read config" ON public.chat_config;
CREATE POLICY "Allow admin read config" ON public.chat_config
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.usuarios
            WHERE usuarios.id = auth.uid()
            AND (usuarios.rol = 'admin' OR usuarios.rol = 'superadmin' OR usuarios.rol = 'super admin')
        )
    );

DROP POLICY IF EXISTS "Allow admin update config" ON public.chat_config;
CREATE POLICY "Allow admin update config" ON public.chat_config
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM public.usuarios
            WHERE usuarios.id = auth.uid()
            AND (usuarios.rol = 'admin' OR usuarios.rol = 'superadmin' OR usuarios.rol = 'super admin')
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.usuarios
            WHERE usuarios.id = auth.uid()
            AND (usuarios.rol = 'admin' OR usuarios.rol = 'superadmin' OR usuarios.rol = 'super admin')
        )
    );

-- Políticas para chat_logs: permitir todo para desarrollo/admin, y lectura/escritura si corresponde
DROP POLICY IF EXISTS "Allow public read/write logs" ON public.chat_logs;
CREATE POLICY "Allow public read/write logs" ON public.chat_logs
    FOR ALL USING (true) WITH CHECK (true);

COMMENT ON TABLE public.chat_config IS 'Configuración activa del asistente de IA del CRM';
COMMENT ON TABLE public.chat_logs IS 'Registro histórico de conversaciones del chat';
