-- MODIFICACIÓN SEGURA DEL ESQUEMA (Sincronización v5.4)
-- NOTA: Se han comentado los DROP TABLE para evitar pérdida accidental de datos.
-- Si necesitas borrar todo de nuevo, descomenta las líneas de abajo.

-- 1. Eliminar tablas (¡CUIDADO! Esto borra todos tus datos actuales)
-- DROP TABLE IF EXISTS public.reg_gastos CASCADE;
-- DROP TABLE IF EXISTS public.reg_viajes CASCADE;
-- DROP TABLE IF EXISTS public.usuarios CASCADE;
-- DROP TABLE IF EXISTS public.cat_choferes CASCADE;
-- DROP TABLE IF EXISTS public.cat_unidades CASCADE;
-- DROP TABLE IF EXISTS public.cat_clientes CASCADE;
-- DROP TABLE IF EXISTS public.cat_proveedores CASCADE;
-- DROP TABLE IF EXISTS public.reg_cuentas CASCADE;
-- DROP TABLE IF EXISTS public.reg_liquidaciones CASCADE;

-- 2. Crear Tabla de Usuarios
CREATE TABLE IF NOT EXISTS public.usuarios (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    usuario TEXT NOT NULL,
    password TEXT, 
    rol TEXT,
    id_contacto TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Crear Tabla de Choferes
CREATE TABLE IF NOT EXISTS public.cat_choferes (
    id_chofer TEXT PRIMARY KEY,
    nombre TEXT NOT NULL,
    licencia TEXT,
    telefono TEXT,
    id_unidad TEXT, -- Unidad asignada
    estatus TEXT DEFAULT 'Activo',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Crear Tabla de Viajes
CREATE TABLE IF NOT EXISTS public.reg_viajes (
    id_viaje TEXT PRIMARY KEY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    id_unidad TEXT,
    id_chofer TEXT,
    cliente TEXT,
    origen TEXT,
    destino TEXT,
    monto_flete NUMERIC(12,2) DEFAULT 0,
    estatus_viaje TEXT DEFAULT 'Pendiente', -- 'Pendiente', 'Liquidado'
    comision_chofer NUMERIC(12,2) DEFAULT 0,
    estatus_pago TEXT DEFAULT 'Pendiente', -- 'Pendiente', 'Pagado'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Crear Tabla de Gastos
CREATE TABLE IF NOT EXISTS public.reg_gastos (
    id_gasto TEXT PRIMARY KEY,
    id_viaje TEXT, 
    id_unidad TEXT, 
    id_unit_eco TEXT, -- Para coincidir con JS (a veces usa id_unidad o id_unit_eco)
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    concepto TEXT,
    monto NUMERIC(12,2) DEFAULT 0,
    es_deducible TEXT DEFAULT 'Sí', -- 'Sí', 'No'
    tipo_pago TEXT DEFAULT 'Efectivo',
    id_chofer TEXT,
    kmts_anteriores INTEGER DEFAULT 0,
    kmts_actuales INTEGER DEFAULT 0,
    kmts_recorridos INTEGER DEFAULT 0,
    litros_rellenados NUMERIC(10,2) DEFAULT 0,
    ticket_foto TEXT, 
    foto_tacometro TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    estatus_pago TEXT DEFAULT 'Pendiente', -- 'Pendiente', 'Pagado'
    forma_pago TEXT DEFAULT 'Contado',     -- 'Contado', 'Crédito'
    estatus_aprobacion TEXT DEFAULT 'Pendiente', -- 'Pendiente', 'Aprobado', 'Rechazado'
    acreedor_nombre TEXT                    -- Chofer, Cliente o Proveedor (para crédito)
);

-- 6. Tabla de Unidades
CREATE TABLE IF NOT EXISTS public.cat_unidades (
    id_unidad TEXT PRIMARY KEY, -- ECO
    nombre_unidad TEXT,
    placas TEXT,
    modelo TEXT,
    marca TEXT,
    id_chofer TEXT,
    tipo_combustible TEXT DEFAULT 'Diesel',
    estatus TEXT DEFAULT 'Activo',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Tabla de Clientes
CREATE TABLE IF NOT EXISTS public.cat_clientes (
    id_cliente TEXT PRIMARY KEY,
    nombre_cliente TEXT,
    razon_social TEXT,
    rfc TEXT,
    contacto_nombre TEXT,
    email TEXT,
    telefono TEXT,
    estatus TEXT DEFAULT 'Activo',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Tabla de Proveedores (Acreedores)
CREATE TABLE IF NOT EXISTS public.cat_proveedores (
    id_proveedor TEXT PRIMARY KEY,
    nombre_proveedor TEXT,
    tipo_proveedor TEXT, -- 'Diesel', 'Refacciones', etc.
    telefono TEXT,
    estatus TEXT DEFAULT 'Activo',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Tabla de Cuentas (Tesorería / Anticipos / Deudas)
CREATE TABLE IF NOT EXISTS public.reg_cuentas (
    id_cuenta TEXT PRIMARY KEY, -- 'ACC-...' o 'CXC-...'
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    tipo TEXT, -- 'A Favor' (Anticipo), 'En Contra' (Deuda/CXP)
    actor_nombre TEXT, -- Chofer o Cliente
    concepto TEXT,
    monto NUMERIC(12,2) DEFAULT 0,
    id_viaje TEXT, -- Referencia opcional
    no_interno TEXT, -- Referencia opcional
    id_gasto_ref TEXT, -- Referencia si viene de un gasto a crédito
    estatus TEXT DEFAULT 'No Liquidado', -- 'No Liquidado', 'Liquidado'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Tabla de Liquidaciones (Log de cortes)
CREATE TABLE IF NOT EXISTS public.reg_liquidaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_chofer TEXT,
    fecha_inicio DATE,
    fecha_fin DATE,
    total_fletes NUMERIC(12,2),
    total_gastos NUMERIC(12,2),
    monto_comision NUMERIC(12,2),
    monto_neto NUMERIC(12,2),
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- Habilitar RLS
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reg_viajes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reg_gastos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cat_choferes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cat_unidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cat_clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cat_proveedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reg_cuentas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reg_liquidaciones ENABLE ROW LEVEL SECURITY;

-- Políticas (Permisivas para desarrollo)
CREATE POLICY "Allow public all" ON public.reg_viajes FOR ALL USING (true);
CREATE POLICY "Allow public all" ON public.reg_gastos FOR ALL USING (true);
CREATE POLICY "Allow public all" ON public.usuarios FOR ALL USING (true);
CREATE POLICY "Allow public all" ON public.cat_choferes FOR ALL USING (true);
CREATE POLICY "Allow public all" ON public.cat_unidades FOR ALL USING (true);
CREATE POLICY "Allow public all" ON public.cat_clientes FOR ALL USING (true);
CREATE POLICY "Allow public all" ON public.cat_proveedores FOR ALL USING (true);
CREATE POLICY "Allow public all" ON public.reg_cuentas FOR ALL USING (true);
CREATE POLICY "Allow public all" ON public.reg_liquidaciones FOR ALL USING (true);
